# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Instagram_development

test:
  <<: *default
  database: Instagram_test

 production:
  <<: *default
  database: Instagram_production
  username: Instagram
  password: <%= ENV['Instagram_DATABASE_PASSWORD'] %>
